
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '015814CAB2BB569228BDD18F29F5F13F'
    
_lr_action_items = {'DOTS':([21,],[24,]),'DO':([4,],[14,]),'END':([2,9,10,11,12,13,19,20,22,23,25,26,27,28,],[-4,-3,-10,-6,-9,-11,-4,-5,-12,25,-7,-4,28,-8,]),'FOR':([0,2,6,9,10,11,12,13,19,20,22,25,26,28,],[1,1,1,-3,-10,-6,-9,-11,1,-5,-12,-7,1,-8,]),'PUTS':([0,2,6,9,10,11,12,13,19,20,22,25,26,28,],[3,3,3,-3,-10,-6,-9,-11,3,-5,-12,-7,3,-8,]),'ARRAYEACH':([0,2,6,9,10,11,12,13,19,20,22,25,26,28,],[4,4,4,-3,-10,-6,-9,-11,4,-5,-12,-7,4,-8,]),'NUMBER':([3,16,17,18,24,],[12,12,21,12,26,]),'LOOPVAR':([14,],[19,]),'EQUAL':([7,],[16,]),'IN':([8,],[17,]),'OPERATOR':([10,11,12,13,20,22,],[-10,18,-9,-11,18,18,]),'STRING':([3,16,18,],[10,10,10,]),'IDENTIFIER':([0,1,2,3,6,9,10,11,12,13,16,18,19,20,22,25,26,28,],[7,8,7,13,7,-3,-10,-6,-9,-11,13,13,7,-5,-12,-7,7,-8,]),'$end':([0,2,5,6,9,10,11,12,13,15,20,22,25,28,],[-2,-4,0,-2,-3,-10,-6,-9,-11,-1,-5,-12,-7,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'stmnts':([0,2,6,19,26,],[6,9,6,23,27,]),'val':([3,16,18,],[11,20,22,]),'exp':([0,6,],[5,15,]),'stmnt':([0,2,6,19,26,],[2,2,2,2,2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> stmnts exp','exp',2,'p_exp_start','myparser.py',34),
  ('exp -> <empty>','exp',0,'p_exp_empty','myparser.py',39),
  ('stmnts -> stmnt stmnts','stmnts',2,'p_exp_stmnts','myparser.py',43),
  ('stmnts -> <empty>','stmnts',0,'p_stmnt_empty','myparser.py',52),
  ('stmnt -> IDENTIFIER EQUAL val','stmnt',3,'p_exp_assign','myparser.py',56),
  ('stmnt -> PUTS val','stmnt',2,'p_exp_puts','myparser.py',60),
  ('stmnt -> ARRAYEACH DO LOOPVAR stmnts END','stmnt',5,'p_exp_iter','myparser.py',65),
  ('stmnt -> FOR IDENTIFIER IN NUMBER DOTS NUMBER stmnts END','stmnt',8,'p_exp_for','myparser.py',69),
  ('val -> NUMBER','val',1,'p_exp_val_num','myparser.py',73),
  ('val -> STRING','val',1,'p_exp_val_str','myparser.py',78),
  ('val -> IDENTIFIER','val',1,'p_exp_val_id','myparser.py',82),
  ('val -> val OPERATOR val','val',3,'p_exp_val_op','myparser.py',86),
]
